Repository CFD-GO/TCLB, pull requests merged in 2019-10, with the labels that each got.

#227 Feature obey system $compilerbindir
  src/configure.ac
Labels: up to debate

#229 Change to solver as a pointer for cleanup before MPI_Finilize
  src/main.cpp.Rt
Labels: bug

#231 D3Q27Q27 heat model
  example/data/Plate_128x2x128.stl
  example/data/chipset_radiator.png
  example/data/chipset_radiator.stl
  models/heat/d3q27q27_cm_cht/Description.md
  models/heat/d3q27q27_cm_cht/Dynamics.R
  models/heat/d3q27q27_cm_cht/Dynamics.c.Rt
  models/heat/d3q27q27_cm_cht/conf.mk
Labels: model

#236 Correcting xml documentation generation
  doc/elements.yaml
  tools/gen.doc.R
Labels: bug

#234 HDF5 / Xdmf support
  doc/elements.yaml
  src/Handlers/cbHDF5.cpp
  src/Handlers/cbHDF5.h
  src/Solver.h.Rt
  src/config.h.in
  src/config.mk.in
  src/configure.ac
  src/glue.hpp
  src/hdf5Lattice.cpp.Rt
  src/hdf5Lattice.h
  src/makefile.main.Rt
Labels: enhancement

#235 XPath based modification
  src/config.mk.in
  src/main.cpp
  src/makefile.main.Rt
  src/xpath_modification.cpp
  src/xpath_modification.h
Labels: enhancement

#238 Updates for moving to sm_30
  .travis.yml
  src/Geometry.cpp.Rt
  src/Handlers/acOptSolve.cpp
  src/Handlers/acSAdjoint.cpp
  src/Handlers/acSolve.cpp
  src/Handlers/acUSAdjoint.cpp
  src/cross.h
Labels: bug
