Repository CFD-GO/TCLB, pull requests merged in 2020-05, with the labels that each got.

#281 Thermo pull request
  example/multiphase/d3q27_pf_velocity/BubbleMa001.xml
  example/multiphase/d3q27_pf_velocity/BubbleMa010.xml
  example/multiphase/d3q27_pf_velocity/BubbleMa100.xml
  example/multiphase/d3q27_pf_velocity/DropletMigrationBenchmark.xml
  example/multiphase/d3q27_pf_velocity/LayeredThermocapillaryFlow_v2_majidiPaper.xml
  example/multiphase/d3q27_pf_velocity/LayeredThermocapillaryFlow_v2_majidiPaper_K5.xml
  models/multiphase/d3q27_pf_velocity/Dynamics.R
  models/multiphase/d3q27_pf_velocity/Dynamics.c.Rt
  models/multiphase/d3q27_pf_velocity/conf.mk
Labels: model

#286 Python 2.X is out-of-life.
  src/Geometry.cpp.Rt
  src/Handlers/cbPythonCall.cpp
  src/configure.ac
Labels: python

#284 Correcting particle support for paranoid compilation
  src/BallTree.h
  src/Lattice.cu.Rt
  src/Particle.hpp
Labels: DEM, enhancement

#287 Fixing bug in atomicSumWarpArr
  src/cross.hpp
Labels: DEM, bug

#289 Feature/stl
  src/Geometry.cpp.Rt
Labels: enhancement
