Repository CFD-GO/TCLB, pull requests merged in 2020-09, with the labels that each got.

#313 Test for empty unit
  src/conf.R
Labels: bug

#316 Install.sh rewrite, GitHub Actions support and MacOS support
  .github/workflows/test.yml
  .travis.yml
  src/Handlers/OptimalControl.cpp.Rt
  src/Handlers/OptimalControlSecond.cpp.Rt
  src/Handlers/acAndersen.cpp
  src/Handlers/acFDTest.cpp
  tools/env.sh
  tools/install.sh
Labels: enhancement

#307 Generic SCMP model
  example/multiphase/scmp/drop.xml
  models/multiphase/d2q9_scmp/Dynamics.R
  models/multiphase/d2q9_scmp/Dynamics.c.Rt
  models/multiphase/d2q9_scmp/ForceTerms_to_Rtemplate.ipynb
  models/multiphase/d2q9_scmp/Forces.R
  models/multiphase/d2q9_scmp/conf.mk
Labels: model

#318 Correcting for edge cases
  src/Solver.cpp.Rt
  src/ZoneSettings.h
  src/conf.R
Labels: bug

#319 Example of initalization using RunR
  example/data/japan.png
  example/runr/advection_diffusion_fields.xml
  models/PDE/advection_diffusion2D/Dynamics.R
  models/PDE/advection_diffusion2D/Dynamics.c
  models/PDE/advection_diffusion2D/conf.mk
Labels: documentation, model

#279 Doxygen
  src/conf.doxygen
  src/docs-by-doxygen/README.md
  src/docs-by-doxygen/cfd-go-logo.png
  src/docs-by-doxygen/conf.doxygen
  src/makefile.main.Rt
Labels: enhancement

#320 Add meaningfull error on wrong Dynamics.R file
  src/conf.R
Labels: enhancement

#321 Article run files
  example/article/ThermocapillaryFlow/BubbleInteraction_catalyst.py
  example/article/ThermocapillaryFlow/BubbleMa001.xml
  example/article/ThermocapillaryFlow/BubbleMa010.xml
  example/article/ThermocapillaryFlow/BubbleMa100.xml
  example/article/ThermocapillaryFlow/DropletMigrationBenchmark.xml
  example/article/ThermocapillaryFlow/LayeredThermocapillaryFlow_v2_majidiPaper.xml
  example/article/ThermocapillaryFlow/LayeredThermocapillaryFlow_v2_majidiPaper_K5.xml
  example/article/ThermocapillaryFlow/README.md
  example/article/ThermocapillaryFlow/Recalcitrant_Investigation_interaction.py
  example/article/ThermocapillaryFlow/images_varyingSizeBubble_01.py
  example/article/ThermocapillaryFlow/recalcitrantBubble_interaction_05rT_1rL_sep_4rL.xml
  example/article/ThermocapillaryFlow/recalcitrantBubble_interaction_1rT_1rL_sep_4rL.xml
  example/article/ThermocapillaryFlow/recalcitrantBubble_interaction_1rT_1rL_sep_6rL.xml
  example/article/ThermocapillaryFlow/recalcitrantBubble_interaction_1rT_1rL_sep_8rL.xml
  example/article/ThermocapillaryFlow/recalcitrantBubble_interaction_2rT_1rL_sep_4rL.xml
  example/article/ThermocapillaryFlow/recalcitrantBubble_interaction_Basecase.xml
  example/article/ThermocapillaryFlow/recalcitrantBubble_r1000_constTemp.xml
  example/article/ThermocapillaryFlow/recalcitrantBubble_r100_constTemp.xml
  example/article/ThermocapillaryFlow/recalcitrantBubble_r10_constTemp.xml
  example/article/ThermocapillaryFlow/recalcitrantBubble_r1_constTemp.xml
  example/article/ThermocapillaryFlow/recalcitrantBubble_r2_constTemp.xml
  example/article/ThermocapillaryFlow/recalcitrantBubble_radius_250.xml
  example/article/ThermocapillaryFlow/recalcitrantBubble_radius_325.xml
  example/article/ThermocapillaryFlow/recalcitrantBubble_radius_400.xml
  example/multiphase/csf/RayleighTaylorInstability_3D.xml
  example/multiphase/d3q27_pf_velocity/ContactAngle_45.xml
  example/multiphase/d3q27_pf_velocity/ContactAngle_45_symX.xml
  example/multiphase/d3q27_pf_velocity/ContactAngle_45_symXZ.xml
  example/multiphase/d3q27_pf_velocity/RayleighTaylorInstability_3D.xml
Labels: documentation, model

#323 Correcting error in tools/dep.R
  tools/dep.R
Labels: bug
