Repository CFD-GO/TCLB, pull requests merged in 2020-10, with the labels that each got.

#326 + Tidy up of 3D phase field method
  models/multiphase/d3q27_pf_velocity/Dynamics.R
  models/multiphase/d3q27_pf_velocity/Dynamics.c.Rt
  models/multiphase/d3q27_pf_velocity/conf.mk
Labels: model

#325 Fixing issue with mpi compilation options discovery
  src/config.mk.in
  src/configure.ac
Labels: bug

#327 Update to readme
  README.md
  tools/install.sh
Labels: documentation

#328 Update unstable branch with develop
  README.md
  models/multiphase/d3q27_pf_velocity/Dynamics.R
  models/multiphase/d3q27_pf_velocity/Dynamics.c.Rt
  models/multiphase/d3q27_pf_velocity/conf.mk
  src/config.mk.in
  src/configure.ac
  tools/install.sh
Labels: propagation

#329 Correcting typo in GRID3D option
  src/LatticeContainer.inc.cpp.Rt
Labels: bug
