Repository CFD-GO/TCLB, pull requests merged in 2020-04, with the labels that each got.

#273 [hotfix] Change of dep.R call
  src/makefile.main.Rt
  tools/dep.R
Labels: bug, hotfix

#274 [propagation] 273 hotfix to develop
  README.md
  src/makefile.main.Rt
  tools/dep.R
Labels: propagation

#276 Fixed string type error in cbFailcheck::DoIt
  src/Handlers/cbFailcheck.cpp
Labels: bug

#275 Adding XML Schemas
  .travis.yml
  doc/elements.yaml
  src/Model.md.Rt
  src/catalog.xml.Rt
  src/conf.R
  src/makefile.main.Rt
  src/schema.xsd.Rt
  tools/deploy.docs.sh
  tools/install.sh
Labels: enhancement
