Repository CFD-GO/TCLB, pull requests merged in 2020-01, with the labels that each got.

#254 Fix a bug in Failcheck
  src/Handlers/cbFailcheck.cpp.Rt
Labels: bug

#253 + Issue with d2q9_pf_velocity clean up and fix + example
  example/multiphase/d2q9_pf_velocity/Droplet_Falling_2D.xml
  models/multiphase/d2q9_pf_velocity/Dynamics.R
  models/multiphase/d2q9_pf_velocity/Dynamics.c.Rt
  models/multiphase/d2q9_pf_velocity/conf.mk
Labels: model

#258 Switching the coverage testing to codecov
  .codecov.yaml
  .travis.yml
  README.md
  src/conf.R
  src/configure.ac
  src/makefile.main.Rt
  tools/cp_line
Labels: bug

#261 Cleanup of tools
  .gitignore
  .travis.yml
  src/compare.cpp
  src/conf.R
  src/config.main.mk.in
  src/config.mk.in
  src/makefile.main.Rt
  tools/coveralls.sh
  tools/createTest.sh
  tools/fun_v3.R
  tools/install.sh
  tools/makeData.R
  tools/makeheaders.c
  tools/myindent
  tools/tests
  tools/tests.sh
  tools/tth
Labels: obsolete

#264 Correcting the include statements for libraries
  src/Geometry.cpp.Rt
  src/Handlers/cbPythonCall.cpp
  src/Lattice.cu.Rt
  src/LatticeAccess.inc.cpp.Rt
  src/LatticeContainer.inc.cpp.Rt
  src/Region.h
  src/RemoteForceInterface.h
  src/Sampler.cpp.Rt
  src/Sampler.h
  src/Solver.cpp.Rt
  src/cross.h
  src/gpu_anim.h
  src/vtkOutput.cpp
Labels: enhancement

#263 Fix logging of RayleighTaylor points in d2q9_pf_velocity
  example/multiphase/d2q9_pf_velocity/RTI_template.xml.Rt
  models/multiphase/d2q9_pf_velocity/Dynamics.R
  models/multiphase/d2q9_pf_velocity/Dynamics.c.Rt
Labels: enhancement, model

#266 Fixing C++11 issues in compare
  src/compare.cpp
Labels: bug
