Repository CFD-GO/TCLB, pull requests merged in 2021-07, with the labels that each got.

#357 + fix typo in surf force calculation (thermocapillary)
  models/multiphase/d3q27_pf_velocity/Dynamics.c.Rt
Labels: bug, model

#359 Feature checkpoint
  doc/elements.yaml
  example/flow/2d/karman_checkpointExample.xml
  src/Handlers/cbSaveCheckpoint.cpp
  src/Handlers/cbSaveCheckpoint.h
  src/Lattice.cu.Rt
  src/Lattice.h.Rt
  src/Solver.cpp.Rt
Labels: enhancement

#360 Passing arguments to lammps/liggghts
  src/lammps.cpp
Labels: DEM
