Repository CFD-GO/TCLB, pull requests merged in 2021-08, with the labels that each got.

#361 Correcting the exit from lammps wrapper
  src/lammps.cpp
Labels: DEM, bug

#363 On recovering 2nd order convergence of lbm with reaction type source terms
  README.md
  example/reaction/d2q9_AllenCahn_SourceTerm_SOI.xml
  example/reaction/d2q9_AllenCahn_SourceTerm_SOI_runr.xml
  models/reaction/d2q9_AllenCahn_SourceTerm_SOI/Dynamics.R
  models/reaction/d2q9_AllenCahn_SourceTerm_SOI/Dynamics.c.Rt
  models/reaction/d2q9_AllenCahn_SourceTerm_SOI/conf.mk
Labels: model

#365 Option for converting standard xml file to ArbitraryLattice automatically
  src/Connectivity.cpp
  src/Connectivity.h
  src/Solver.cpp
  src/Solver.h
  src/lists.mk
  src/main.cpp
  src/toArb.cpp
  src/toArb.h
Labels: enhancement, arbitrary, unstable
