Repository CFD-GO/TCLB, pull requests merged in 2022-05, with the labels that each got.

#390 D2q9 reaction diffusion configurable upgrade
  models/reaction/d2q9_reaction_diffusion_system/Dynamics.R
  models/reaction/d2q9_reaction_diffusion_system/Dynamics.c.Rt
  models/reaction/d2q9_reaction_diffusion_system/conf.mk
Labels: model

#394 Fixing bug in setting zone number in Control
  src/Handlers/conControl.cpp.Rt
Labels: bug

#398 Adding force averaging to simplepart
  src/simplepart.cpp
Labels: DEM
