Repository CFD-GO/TCLB, pull requests merged in 2023-01, with the labels that each got.

#413 Introduction of storage types
  .github/actions/configure/action.yaml
  .github/actions/install/action.yaml
  .github/workflows/storage_test.yml
  models/flow/d2q9/Dynamics.R
  src/Global.h.Rt
  src/Lattice.cu.Rt
  src/Lattice.h.Rt
  src/LatticeAccess.inc.cpp.Rt
  src/LatticeContainer.inc.cpp.Rt
  src/conf.R
  src/config.h.in
  src/configure.ac
  src/cross.h
  src/types.h
Labels: enhancement

#423 Fixing bugs in configure and compile
  src/configure.ac
  src/hdf5Lattice.cpp.Rt
Labels: bug

#417 Fix current issue #416 and addition of extra boundary conditions for d3q27_pf_velocity
  models/multiphase/d2q9_pf_velocity/Dynamics.R
  models/multiphase/d2q9_pf_velocity/Dynamics.c.Rt
  models/multiphase/d3q27_pf_velocity/Dynamics.R
  models/multiphase/d3q27_pf_velocity/Dynamics.c.Rt
  models/multiphase/d3q27_pf_velocity/conf.mk
Labels: model

#424 Changing macro name to avoid name-collision with Rcpp
  src/LatticeAccess.inc.cpp.Rt
  src/config.h.in
  src/configure.ac
  src/types.h
Labels: bug
